name: dotnet package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      dllName: VoteMap

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Prepare files
        run: |
          mkdir -p package/${dllName}
          cp -r VoteMap/bin/Release/net8.0/* package/${dllName}/
          cd package
          zip -r ${dllName}.zip ${dllName}

      - name: Create GitHub Release
        run: |
          gh release create ${{ github.ref_name }} \
            package/${dllName}.zip \
            --title "Release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}